In [10]:
import numpy as np
import scipy
import cv2
from WalshHadamardTransform import WHTTree
import time

In [11]:
sourceImage = cv2.imread("OceanImage.jpg")
sourceImageYCC = cv2.cvtColor(sourceImage, cv2.COLOR_BGR2YCR_CB)
sourceY, sourceCr, sourceCb = cv2.split(sourceImageYCC)

IMAGE_HEIGHT, IMAGE_WIDTH = sourceImageYCC.shape[:2]

In [13]:
m = 3
p = 2 ** m  # window(patch) size
numOfBaseY = 16
numOfBaseC = 4

startTime = int(round(time.time() * 1000))
#
treeY = WHTTree(sourceY, p, numOfBaseY)
treeCr = WHTTree(sourceCr, p, numOfBaseC)
treeCb = WHTTree(sourceCb, p, numOfBaseC)
#
endTime = int(round(time.time() * 1000))
elapse = endTime - startTime
print('time elapse = ', elapse)

('time elapse = ', 2023)


In [14]:
PATCHES_HEIGHT, PATCHES_WIDTH = treeY[-1:][0].shape  # 593, 793 for 600*800
kdTreeInput = []

startTime = int(round(time.time() * 1000))
#
for i in xrange(0, PATCHES_HEIGHT):
    for j in xrange(0, PATCHES_WIDTH):
        vector = []  # 24d vector for one patch
        for dimention in treeY[-numOfBaseY:]:
            vector.append(dimention[i, j])
        for dimention in treeCr[-numOfBaseC:]:
            vector.append(dimention[i, j])
        for dimention in treeCb[-numOfBaseC:]:
            vector.append(dimention[i, j])
        kdTreeInput.append(vector)
#
endTime = int(round(time.time() * 1000))
elapse = endTime - startTime
print('time elapse = ', elapse)

('time elapse = ', 6627)


In [17]:
kdTreeInput[10]

[2919,
 57,
 13,
 15,
 -71,
 15,
 15,
 -11,
 -91,
 71,
 47,
 9,
 -45,
 9,
 13,
 -85,
 7408,
 0,
 16,
 0,
 1344,
 0,
 0,
 0]

In [ ]:
# playground

In [10]:
testMatrix0 = np.array([[1,2,3,4], [5,6,7,8], [9,0,1,2]], dtype=int)
print(testMatrix0)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]


In [13]:
testMatrix1 = np.array([[9,0,1,2], [1,2,3,4], [5,6,7,8]], dtype=int)
print(testMatrix1)

[[9 0 1 2]
 [1 2 3 4]
 [5 6 7 8]]


In [14]:
testMatrix2 = np.array([[5,6,7,8], [9,0,1,2], [1,2,3,4]], dtype=int)
print(testMatrix2)

[[5 6 7 8]
 [9 0 1 2]
 [1 2 3 4]]


In [15]:
matrixList = [testMatrix0, testMatrix1, testMatrix2]
print(matrixList)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]]), array([[9, 0, 1, 2],
       [1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[5, 6, 7, 8],
       [9, 0, 1, 2],
       [1, 2, 3, 4]])]


In [18]:
for matrix in matrixList[-2:]:
    #matrix = matrix.flatten()
    print(matrix[0, 0])

9
5


In [36]:
matrixList

[array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 1, 2]]), array([[9, 0, 1, 2],
        [1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[5, 6, 7, 8],
        [9, 0, 1, 2],
        [1, 2, 3, 4]])]

In [41]:
testMatrix2.shape

(3, 4)